### ISSUE TITLE
扫描时机

### ISSUE THREAD

**Issue by shingohu** [aicareles/Android-BLE#33]
扫描连接在Ble: Service connection successful 执行之前会导致连接不成功
能否有一个Ble: Service connection successful的回调

**Comment by aicareles** [comment]
任何接口都要在初始化之后才可以调用

**Comment by shingohu** [comment]
初始化了,但是这个Ble: Service connection successful 不确定什么时候执行,一进入app就初始化 扫描连接,如果Ble: Service connection successful还未执行到就会连接不上

**Comment by shingohu** [comment]
新版本已经使用代理代替了之前使用Service进行操作的方式,问题不存在了
