### ISSUE TITLE
关于stopScan的问题

### ISSUE THREAD

**Issue by shingohu** [aicareles/Android-BLE#41]
1、BluetoothScannerImplLollipop 中stopScan 会优先回调(super.stopScan())给调用方，是否应该放到scanner.stopScan(scannerCallback);后面
有一个场景是这样的,搜索指定设备,没有搜索到(搜索超时)时,希望继续搜索,所以我在onStop的回调中执行了startScan进行重新搜索,但是此时scanner.stopScan(scannerCallback)还未执行到,又开始了下次搜索,会报错SCAN_FAILED_ALREADY_STARTED 

2、在超时扫描onStop前关闭蓝牙,然后开启蓝牙不会继续扫描设备了 isScaning一直是true. 
ScanRequest 中stopScan isEnableInternal 当蓝牙关闭时判断为false ,导致没有走后面的停止流程
此问题demo可复现

**Comment by aicareles** [comment]
感谢，最新源码已修复该问题

**Comment by shingohu** [comment]
> 感谢，最新源码已修复该问题

还没发吧
