### ISSUE TITLE
文档

### ISSUE THREAD

**Issue by zhaoxiuyu** [aicareles/Android-BLE#46]
文档写的真是乱，能不能好好整理一下。。

**Comment by aicareles** [comment]
感谢你的建议，后面会重新编写文档，以及接入流程，与后面新增加的功能一起更新，感谢关注

**Comment by zhaoxiuyu** [comment]
@aicareles  现在的最新版本是3.0.5吗， 我按照你的文档接入步奏 都走不通啊。 接入文档上面 setMaxConnectNum 这个方法没有，create 方法我看代码里面是没有接口回调的。

**Comment by aicareles** [comment]
不好意思，这两天刚更新的文档，最新jcenter依赖版本是3.0.5，但demo以及文档是3.1.0的，可能会有个别新添加的接口找不到，后面会提交到jcenter，你可以先依赖库源码


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shimmer"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月30日(星期四) 下午3:19
收件人:&nbsp;"aicareles/Android-BLE"<Android-BLE@noreply.github.com&gt;;
抄送:&nbsp;"艾神一不小心"<823581722@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [aicareles/Android-BLE] 文档 (#46)





 
@aicareles  现在的最新版本是3.0.5吗， 我按照你的文档接入步奏 都走不通啊。 接入文档上面 setMaxConnectNum 这个方法没有，create 方法我看代码里面是没有接口回调的。

**Comment by zhaoxiuyu** [comment]
@aicareles  连接出错，一直是2521。   我用你的APK，也是连接不上，一直是2031.

**Comment by aicareles** [comment]
那就是连接失败，建议检查下硬件，或者确定硬件设备为ble设备，如果想更准备的验证问题，建议先使用nrf软件连接，看是否能成功



---原始邮件---
发件人: "zhaoxiuyu"<notifications@github.com&gt;
发送时间: 2020年4月30日(周四) 下午5:19
收件人: "aicareles/Android-BLE"<Android-BLE@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Allen Iverson"<823581722@qq.com&gt;;
主题: Re: [aicareles/Android-BLE] 文档 (#46)




 
@aicareles  连接出错，一直是2521。   我用你的APK，也是连接不上，一直是2031.

**Comment by zhaoxiuyu** [comment]
@aicareles  我也不太懂这个。不知道是不是BLE设备。说明书上写的是 Bluetooth 4.0 +LE 。
